### PR TITLE
Use ha-blueprint

### LINKED ISSUE #1: Do you want me to add GitHub actions?
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

### PR DESCRIPTION
**Pull request by KTibow**
Fixes #1

### CODE REVIEW

**Comment by rsnodgrass** [comment]
@ktibow Thanks!

**Comment by rsnodgrass** [comment]
@KTibow what is the best way to override/change the defaults for code formatting?  For example, overriding the formatting for line length when wrapping occurs to be longer.  Thanks

**Comment by KTibow** [comment]
Use isort or flake8 config files

**Comment by rsnodgrass** [comment]
@KTibow can you point me to a quick example where someone extends ha-blueprint's default formatting to change something?   I want to convert several more repositories to ha-blueprint, but before I do want to tweak a few things.

**Comment by KTibow** [comment]
I don't think anyone's done that before, it just runs `black .`

**Pull request merged**
